#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# flask-praetorian documentation build configuration file, created by
# sphinx-quickstart on Thu Dec  8 09:38:59 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import json
import os
import setuptools
import sys

project_root = os.path.dirname(os.path.dirname(__file__))
with open(os.path.join(project_root, '.project_metadata.json')) as meta_file:
    project_metadata = json.loads(meta_file.read())
packages = setuptools.find_packages(where=project_root, exclude=['test*'])
unique_roots = set([p.split('.')[0] for p in packages])
full_paths = [os.path.join(project_root, p) for p in unique_roots]
[sys.path.insert(0, p) for p in full_paths]

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
author = project_metadata['author']
project = project_metadata['name']
copyright = project_metadata['copyright']

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# The short X.Y version.
version = project_metadata['version']
# The full version, including alpha/beta/rc tags.
release = project_metadata['release']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.

# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, maps document names to template names.

html_sidebars = {
    '/': [
        'side-links.html',
        'searchbox.html',
    ],
    'index': [
        'side-links.html',
        'searchbox.html',
    ],
    'overview': [
        'side-links.html',
        'searchbox.html',
    ],
}

docs_root = os.path.join(project_root, 'docs')
for (root, dirs, files) in os.walk(docs_root):
    for file in files:
        absolute = os.path.join(root, file)
        relative = os.path.relpath(absolute, start=docs_root)
        (target, ext) = os.path.splitext(relative)
        if ext == '.rst' and target not in ['index', 'overview']:
            html_sidebars[target] = [
                'side-icon.html',
                'localtoc.html',
                'relations.html',
                'side-links.html',
                'searchbox.html',
            ]

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = project_metadata['name'] + 'doc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        project_metadata['name'] + '.tex',
        project_metadata['name'] + ' Documentation',
        project_metadata['author'],
        'manual',
    ),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        project_metadata['name'],
        project_metadata['name'] + ' Documentaion',
        [project_metadata['author']],
        1,
    )
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        project_metadata['name'],
        project_metadata['name'] + ' Documentation',
        project_metadata['author'],
        project_metadata['name'],
        'One line description of project.',
        'Miscellaneous',
    ),
]
